routes/web.php
<?php

// Add proper web handling
Route::prefix('elearning')->middleware(['web', 'addon:elearning'])->name('elearning.')->namespace('Sautor\ELearning\Controllers')->group(function () {
    Route::redirect('/', '/elearning/modulos')->name('index');
    Route::resource('modulos', 'ModulesController')->parameter('modulos', 'module');
    Route::resource('licoes', 'LessonsController')->parameter('licoes', 'lesson')->except(['index']);
    Route::post('licoes/{lesson}/completion', 'LessonsController@storeCompletion')->name('licoes.storeCompletion');
    Route::get('licoes/{lesson}/quiz', 'LessonsController@showQuiz')->name('licoes.showQuiz');
    Route::post('licoes/{lesson}/quiz', 'LessonsController@storeScore')->name('licoes.storeScore');

    Route::post('licoes/{lesson}/anexos', 'LessonsController@addAttachment')->name('licoes.addAttachment');
    Route::delete('licoes/{lesson}/anexos/{media}', 'LessonsController@deleteAttachment')->name('licoes.deleteAttachment');

    Route::get('grupo/{grupo}', 'ModulesController@grupo')->name('grupo');
});

resources/views/group.blade.php
@extends('elearning::layouts.main')

@php($hero = Setting::get('grupo-'.$grupo->id.'-hero'))
@section('el.hero')
  <div class="el-hero el-hero--group"
       @if($hero) style="background-image: url({{ $hero }})" @endif
  >
    <div class="el-hero__body">
      <div class="container-fluid">
        @if($grupo->logo)
          <img src="{{ $grupo->logo }}" alt="{{ $grupo->nome_curto }}" class="el-hero__logo">
        @else
          <h1 class="el-hero__title">
            {{ $grupo->nome }}
          </h1>
        @endif
      </div>
    </div>
  </div>
@endsection

@section('el.content')

  <div class="el-section">
    <div class="container-fluid">

      @if($grupo->logo)
        <h1>{{ $grupo->nome }}</h1>
      @endunless

        <h2>Módulos públicos</h2>

        @include('elearning::modules.list-component', ['modules' => $publicModules])

    </div>
  </div>

  @can('details', $grupo)
    <div class="el-section el-section--alt">
      <div class="container-fluid">

        <h2>Módulos não públicos</h2>

        @include('elearning::modules.list-component', ['modules' => $privateModules])

        @can('create', \Sautor\ELearning\Models\Module::class)
          @can('update', $grupo)
            <a href="{{ route('elearning.modulos.create') }}?grupo={{ $grupo->id }}" class="btn btn-secondary">
              <span class="far fa-plus"></span>
              <span>Criar módulo</span>
            </a>
          @endcan
        @endcan

      </div>
    </div>
  @endcan

@endsection

resources/views/layouts/main.blade.php
@extends('layouts.basic')
@section('content')
  @include('elearning::layouts.partials.header')
  @yield('el.hero')
  @yield('el.content')
@endsection

resources/views/layouts/partials/header.blade.php
@include('components.addon-header', ['name' => 'eLearning', 'icon' => 'fad fa-graduation-cap', 'url' => route('elearning.index')])

resources/views/lessons/create.blade.php
@extends('elearning::layouts.main')

@section('el.content')
  <div class="el-section">
    <div class="container">
      <h1>Criar Lição</h1>

      @php($scope = 'new-lesson')
      <form action="{{ route('elearning.licoes.store') }}" method="POST" data-vv-scope="{{ $scope }}"
            enctype="multipart/form-data">
        {{ csrf_field() }}

        @include('elearning::lessons.form')

        <button class="btn btn-primary">Criar</button>
      </form>
    </div>
  </div>
@endsection

resources/views/lessons/edit.blade.php
@extends('elearning::layouts.main')

@section('el.content')

  <div class="el-section">
    <div class="container">
      <h1>Editar Lição</h1>

      @php($scope = 'edit-lesson')
      <form action="{{ route('elearning.licoes.update', $lesson) }}" method="POST" data-vv-scope="{{ $scope }}"
            enctype="multipart/form-data">
        @method('PUT')
        @csrf

        @include('elearning::lessons.form')

        <div class="row">
          <div class="col">
            <button type="submit" class="btn btn-primary">Editar</button>
          </div>
          <div class="col col-auto">
            <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#deleteModal">
              <span class="far fa-trash"></span>
              <span>Eliminar</span>
            </button>
          </div>
        </div>

      </form>
    </div>
  </div>

  <div class="modal" id="deleteModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <header class="modal-header">
          <h3 class="modal-title">Eliminar lição</h3>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </header>
        <section class="modal-body">
          <p>Tem a certeza que deseja eliminar a lição <strong>{{ $lesson->title }}</strong>?</p>
        </section>
        <form action="{{ route('elearning.licoes.destroy', $lesson) }}" method="post" class="modal-footer">
          @csrf
          @method('DELETE')
          <button type="button" class="btn btn-link" data-toggle="modal" data-target="#deleteModal">Cancelar</button>
          <button type="submit" class="btn btn-danger">Eliminar</button>
        </form>
      </div>
    </div>
  </div>
@endsection

resources/views/lessons/form.blade.php
@include('forms.input', ['name' => 'title', 'label' => 'Título', 'required' => true])
@include('forms.editor', ['name' => 'description', 'label' => 'Descrição', 'required' => true, 'simple' => true])
@include('forms.editor', ['name' => 'content', 'label' => 'Conteúdo'])
@include('forms.file', ['name' => 'image', 'label' => 'Imagem', 'options' => ['accept' => 'image/*']])
@include('forms.file', ['name' => 'audio', 'label' => 'Ficheiro áudio', 'options' => ['accept' => '.mp3']])
@include('forms.input', ['name' => 'video', 'label' => 'URL de vídeo', 'options' => ['type' => 'url']])
@include('forms.file', ['name' => 'quiz', 'label' => 'Ficheiro de quiz', 'help' => 'O ficheiro de quiz pode ser gerado no <a href="https://catequiz.gitlab.io/creator/#/mini" target="_blank">Catequiz Creator</a>', 'options' => ['accept' => '.json']])
@include('forms.checkbox', ['name' => 'public', 'label' => 'Público'])

<div class="row">
  <div class="col col-sm">
    @include('forms.select', ['name' => 'module_id', 'label' => 'Módulo', 'required' => true, 'list' => $modules->pluck('name', 'id'), 'value' => @$module_id])
  </div>
  <div class="col col-sm">
    @include('forms.input', ['name' => 'order', 'label' => 'Ordem no módulo', 'required' => true, 'options' => ['pattern' => '[0-9]*', 'inputtype' => 'numeric']])
  </div>
</div>

<div class="row">
  <div class="col col-sm">
    @include('forms.input', ['name' => 'published_at', 'label' => 'Data de publicação', 'value' => isset($lesson) && $lesson->published_at ? $lesson->published_at->isoFormat('YYYY-MM-DD[T]HH:mm') : null, 'options' => ['type' => 'datetime-local'], 'help' => 'A lição será visível a partir desta data e hora. Se o campo for deixado em branco, será visível imediatamente.'])
  </div>
  <div class="col col-sm">
    @include('forms.input', ['name' => 'available_at', 'label' => 'Disponível a partir de', 'options' => ['type' => 'datetime-local'], 'value' => isset($lesson) && $lesson->available_at ? $lesson->available_at->isoFormat('YYYY-MM-DD[T]HH:mm') : null, 'help' => 'O conteúdo da lição será visível a partir desta data. Se o campo for deixado em branco, será visível assim que publicada.'])
  </div>
</div>

resources/views/lessons/list-component.blade.php
<div class="lessons-list">
@foreach($lessons as $lesson)
  @php($completion = $lesson->completedBy()->where('pessoa_id', Auth::id())->first())
  @php($lessonTag = $lesson->is_available || Gate::allows('update', $lesson) ? 'a' : 'div')
  <{{ $lessonTag }} @if($lessonTag === 'a') href="{{ route('elearning.licoes.show', $lesson) }}" @endif class="lessons-list__item">

    @if($lesson->image)
      <img src="{{ $lesson->image }}" class="lessons-list__item__image">
    @else
      <div class="lessons-list__item__icon">
        <span class="fas fa-book fa-2x"></span>
      </div>
    @endif

    <div class="lessons-list__item__data">
      <h5 class="lessons-list__item__title">{{ $lesson->title }}</h5>
      <div class="lessons-list__item__desc">
        {!! $lesson->description !!}
      </div>
      @if(!$lesson->is_published)
        <small class="text-muted">
          Esta lição será publicada
          <time title="{{ $lesson->published_at->isoFormat('LLL') }}">{{ $lesson->published_at->diffForHumans() }}</time>
        </small>
      @endif
      @if(!$lesson->is_available)
        <small class="text-muted">
          Esta lição estará disponível
          <time title="{{ $lesson->available_at->isoFormat('LLL') }}">{{ $lesson->available_at->diffForHumans() }}</time>
        </small>
      @endif
        <div class="lessons-list__item__meta">
          @if($lesson->video)
            <span class="lessons-list__item__meta__item">
              <span class="fas fa-film"></span>
            </span>
          @endif
          @if($lesson->audio)
            <span class="lessons-list__item__meta__item">
              <span class="fas fa-volume"></span>
            </span>
          @endif
          @unless(empty($lesson->content))
            <span class="lessons-list__item__meta__item">
              <span class="fas fa-align-left"></span>
            </span>
          @endunless
          @if($lesson->quiz)
            <span class="lessons-list__item__meta__item">
              @include('elearning::partials.icon-catequiz')
              @if($completion && $completion->completion->score !== null)
                <span class="badge badge-light ml-1">{{ $completion->completion->score }}</span>
              @endif
            </span>
          @endif
        </div>
    </div>
    @auth
      @if($completion)
        <div class="lessons-list__item__complete">
          @if($lesson->quiz && $completion->completion->score === null)
            <span class="text-warning">
              <span class="far fa-check-circle fa-lg"></span>
            </span>
          @else
            <span class="text-success">
              <span class="fas fa-check-circle fa-lg"></span>
            </span>
          @endif
        </div>
      @endif
    @endauth
  </{{ $lessonTag }}>
@endforeach
</div>

resources/views/lessons/partials/attachments.blade.php
@if($lesson->hasMedia() || Gate::allows('update', $lesson))

  <div class="row align-items-center mb-3">
    <h2 class="col mb-0">
      Anexos
    </h2>
    @can('update', $lesson)
      <div class="col col-auto">
        <button class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#addAttachmentModal">
          <span class="far fa-plus"></span>
          <span class="d-none d-sm-inline">Adicionar</span>
        </button>
      </div>
    @endcan
  </div>

  @if($errors->isNotEmpty())
    <div class="alert alert-danger">
      Ocorreram alguns erros ao adicionar um anexo:
      <ul>
        @foreach($errors->all() as $message)
          <li>{{ $message }}</li>
        @endforeach
      </ul>
    </div>
  @endif

  @if($lesson->getMedia()->isNotEmpty())
    <div class="sautor-list">
      @foreach($lesson->getMedia() as $media)
        <div class="sautor-list__item">
          @include('elearning::components.file-icon', ['class' => 'mr-2', 'extension' => $media->extension])
          <a href="{{ $media->getUrl() }}" class="sautor-list__item__data">
            <p class="sautor-list__item__name">
              {{ $media->name }}
            </p>
            <p class="sautor-list__item__meta">
              {{ strtoupper($media->extension) }}
              &middot;
              {{ $media->human_readable_size }}
            </p>
          </a>
          <div class="sautor-list__item__actions">
            <a href="{{ $media->getUrl() }}">
              <span class="far fa-cloud-download"></span>
            </a>
            @can('update', $lesson)
              <a href="#" data-toggle="modal" data-target="#delete{{ $media->id }}Modal">
                <span class="far fa-trash"></span>
              </a>
            @endcan
          </div>
        </div>
      @endforeach
    </div>

  @else

    <section class="sautor-list--empty">
      Esta lição não tem anexos.
    </section>

  @endif

@endif

@can('update', $lesson)

  <div class="modal" id="addAttachmentModal">
    <div class="modal-dialog">
      <form class="modal-content" method="POST" enctype="multipart/form-data" action="{{ route('elearning.licoes.addAttachment', $lesson) }}">
        @csrf
        <header class="modal-header">
          <h3 class="modal-title">Adicionar anexo</h3>
          <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
          </button>
        </header>
        <section class="modal-body">
          @include('forms.file', ['name' => 'file', 'label' => 'Ficheiro', 'required' => true])
          @include('forms.input', ['name' => 'name', 'label' => 'Nome', 'help' => 'Por omissão, o anexo terá o nome do ficheiro.'])
        </section>
        <footer class="modal-footer">
          <button class="btn btn-link" type="button" data-toggle="modal" data-target="#addAttachmentModal">Cancelar</button>
          <button class="btn btn-success" type="submit">Adicionar</button>
        </footer>
      </form>
    </div>
  </div>

  @foreach($lesson->getMedia() as $media)
    <div class="modal" id="delete{{ $media->id }}Modal">
      <div class="modal-dialog">
        <form class="modal-content" method="POST" action="{{ route('elearning.licoes.deleteAttachment', [$lesson, $media]) }}">
          @csrf
          @method('DELETE')
          <header class="modal-header">
            <h3 class="modal-title">Eliminar anexo</h3>
            <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
              <span aria-hidden="true">&times;</span>
            </button>
          </header>
          <section class="modal-body">
            <p>Tem a certeza que quer eliminar o anexo <strong>{{ $media->file_name }}</strong> ?</p>
            <p class="text-danger">
              <strong>Atenção!</strong> A eliminação é permanente.
            </p>
          </section>
          <footer class="modal-footer">
            <button class="btn btn-link" type="button" data-toggle="modal" data-target="#delete{{ $media->id }}Modal">Cancelar</button>
            <button class="btn btn-danger" type="submit">Eliminar</button>
          </footer>
        </form>
      </div>
    </div>
  @endforeach
@endcan

resources/views/lessons/show.blade.php
@extends('elearning::layouts.main')

@php($hero = $lesson->image ?? $lesson->module->image ?? Setting::get('grupo-'.$lesson->grupo->id.'-hero'))
@section('el.hero')
  <div class="el-hero @if($hero) has-cover @endif "
       @if($hero) style="background-image: url({{ $hero }})" @elseif($lesson->grupo->cor) style="background-color: {{ $lesson->grupo->cor }}" @endif
  >
    <div class="el-hero__body">
      <div class="container-fluid">
        <h1 class="el-hero__title">
          {{ $lesson->title }}
        </h1>
        <p class="el-hero__desc">
          {!! $lesson->description !!}
        </p>
        @can('update', $lesson)
          <a href="{{ route('elearning.licoes.edit', $lesson) }}" class="btn btn-sm btn-outline-light">
            <span class="fas fa-pencil"></span>
            <span>Editar</span>
          </a>
        @endcan

      </div>
    </div>
  </div>
@endsection

@section('el.content')

  <div class="el-section">
    <div class="container">

      @if(!$lesson->is_published)
        <div class="alert alert-info">
          <h5 class="alert-heading">
            Esta lição não está publicada.
          </h5>
          <p class="mb-0">
            Esta lição será publicada apenas {{ $lesson->published_at->isoFormat('LLLL') }}.
            Até lá, não aparecerá na lista das lições do curso e não poderá ser vista.
          </p>
        </div>
      @elseif(!$lesson->is_available)
        <div class="alert alert-info">
          <h5 class="alert-heading">
            Esta lição não está disponível.
          </h5>
          <p class="mb-0">
            Esta lição ficará disponível apenas a partir de {{ $lesson->available_at->isoFormat('LLLL') }}.
            Até lá, aparecerá na lista das lições do curso mas o seu conteúdo não poderá ser visto.
          </p>
        </div>
      @endif

      @include('elearning::lessons.partials.content')
      @include('elearning::lessons.partials.attachments')


        <div class="row mt-5">
          <div class="col">
            <a href="{{ route('elearning.modulos.show', $lesson->module) }}" class="btn btn-secondary">
              <span class="far fa-arrow-left"></span>
              <span>Voltar ao módulo</span>
            </a>
          </div>
          <div class="col col-auto">
            @auth

              @if($lesson->quiz && $completion && $completion->score !== null)
                <a href="{{ route('elearning.licoes.showQuiz', $lesson) }}" class="btn btn-secondary">
                  @include('elearning::partials.icon-catequiz')
                  <span>Repetir o quiz</span>
                  <span class="far fa-arrow-right"></span>
                </a>
              @elseif($lesson->quiz && $completion)
                <a href="{{ route('elearning.licoes.showQuiz', $lesson) }}" class="btn btn-secondary">
                  @include('elearning::partials.icon-catequiz')
                  <span>Avançar para o quiz</span>
                  <span class="far fa-arrow-right"></span>
                </a>
              @elseif($lesson->quiz)
                <form action="{{ route('elearning.licoes.storeCompletion', $lesson) }}" method="POST">
                  @csrf
                  <button class="btn btn-primary">
                    @include('elearning::partials.icon-catequiz')
                    <span>Terminar e avançar para o quiz</span>
                    <span class="far fa-arrow-right"></span>
                  </button>
                </form>
              @elseif(!$completion)
                <form action="{{ route('elearning.licoes.storeCompletion', $lesson) }}" method="POST">
                  @csrf
                  <button class="btn btn-success">
                    <span>Terminar lição</span>
                    <span class="far fa-arrow-right"></span>
                  </button>
                </form>
              @endif

            @endauth

            @guest
              @if($lesson->quiz)
                <a href="{{ route('elearning.licoes.showQuiz', $lesson) }}" class="btn btn-secondary">
                  @include('elearning::partials.icon-catequiz')
                  <span>Avançar para o quiz</span>
                  <span class="far fa-arrow-right"></span>
                </a>
              @endif
            @endguest
          </div>
        </div>

    </div>
  </div>

  <div class="el-section el-section--alt">
    <div class="container-fluid">

      @can('update', $lesson)
        <h4>Já completaram esta lição</h4>

        @component('pessoas.list-component', [
                                'pessoas' => $lesson->completedBy,
                                'meta' => function($p) {
                                    $meta = $p->completion->created_at->tz('Europe/Lisbon')->isoFormat('LLL');
                                    if ($p->completion->score !== null) {
                                      $meta .= ' &middot; ';
                                      $meta .= view('elearning::partials.icon-catequiz');
                                      $meta .= ' '.$p->completion->score;
                                    }
                                    return $meta;
                                },
                                'empty_message' => 'Ninguém completou esta lição'
                                ])
        @endcomponent
      @endcan

    </div>
  </div>


@endsection

resources/views/modules/create.blade.php
@extends('elearning::layouts.main')

@section('el.content')
  <div class="el-section">
    <div class="container">
      <h1>Criar Módulo</h1>

      @php($scope = 'new-module')
      <form action="{{ route('elearning.modulos.store') }}" method="POST" data-vv-scope="{{ $scope }}"
            enctype="multipart/form-data">
        {{ csrf_field() }}

        @include('elearning::modules.form')

        <button class="btn btn-primary">Criar</button>

      </form>
    </div>
  </div>
@endsection

resources/views/modules/edit.blade.php
@extends('elearning::layouts.main')

@section('el.content')
  <div class="el-section">
    <div class="container">
      <h1>Editar Módulo</h1>

      @php($scope = 'edit-module')
      <form action="{{ route('elearning.modulos.update', $module) }}" method="POST" data-vv-scope="{{ $scope }}"
            enctype="multipart/form-data">
        @method('PUT')
        @csrf

        @include('elearning::modules.form')

        <div class="row">
          <div class="col">
            <button type="submit" class="btn btn-primary">Editar</button>
          </div>
          <div class="col col-auto">
            <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#deleteModal">
              <span class="far fa-trash"></span>
              <span>Eliminar</span>
            </button>
          </div>
        </div>

      </form>

    </div>
  </div>


  <div class="modal" id="deleteModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <header class="modal-header">
          <h3 class="modal-title">Eliminar módulo</h3>
          <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
          </button>
        </header>
        <section class="modal-body">
          <p>Tem a certeza que deseja eliminar o módulo <strong>{{ $module->name }}</strong>?</p>
        </section>
        <form action="{{ route('elearning.modulos.destroy', $module) }}" method="post" class="modal-footer">
          @csrf
          @method('DELETE')
          <button type="button" class="btn btn-link" data-toggle="modal" data-target="#deleteModal">Cancelar</button>
          <button type="submit" class="btn btn-danger">Eliminar</button>
        </form>
      </div>
    </div>
  </div>
@endsection

resources/views/modules/form.blade.php
@include('forms.input', ['name' => 'name', 'label' => 'Nome', 'required' => true])
@include('forms.editor', ['name' => 'description', 'label' => 'Descrição', 'simple' => true, 'required' => true])
@include('forms.file', ['name' => 'image', 'label' => 'Imagem'])
@include('forms.checkbox', ['name' => 'public', 'label' => 'Público'])

<div class="form-group">
  <label class="form-control-label">
    Grupo
    @unless(\Auth::user()->hasRole('administrador')) <span class="text-danger">*</span> @endunless
  </label>
  <grupo-picker name="grupo_id" with-input value="{{ old('grupo_id', $value ?? (isset($formModel) ? $formModel['grupo_id'] : null) ?? null) }}"></grupo-picker>
</div>

resources/views/modules/index.blade.php
@extends('elearning::layouts.main')


@section('el.hero')
  <div class="el-hero has-main-bg has-cover">
    <div class="el-hero__body">
      <div class="container-fluid">
        @auth
          <h1 class="el-hero__title">
            Olá {{ Auth::user()->nome_curto }}!
          </h1>
          <p class="el-hero__lead">
            {{ Auth::user()->genero === 'f' ? 'Bem-vinda' : 'Bem-vindo' }} ao {{ config('app.name') }} eLearning
          </p>
        @endauth
        @guest
          <h1 class="el-hero__title">
            Bem-vindo ao eLearning!
          </h1>
        @endguest
      </div>
    </div>
  </div>
@endsection

@section('el.content')
  <div class="el-section">
    <div class="container-fluid">
      <h2>Módulos públicos</h2>
      @include('elearning::modules.list-component', ['modules' => $publicModules])
    </div>
  </div>

  @auth
    <div class="el-section el-section--alt">
      <div class="container-fluid">
        <h2>Módulos dos meus grupos</h2>

        @unless(empty($modulesFromMyGroups))
          @include('elearning::modules.list-component', [ 'modules' => $modulesFromMyGroups ])
        @else
          <div class="alert alert-secondary">
            Não tem grupos com módulos.
          </div>
        @endunless

        @can('create', \Sautor\ELearning\Models\Module::class)
          <a href="{{ route('elearning.modulos.create') }}" class="btn btn-secondary">
            <span class="far fa-plus"></span>
            <span>Criar módulo</span>
          </a>
        @endcan


        @if($myGroups->isNotEmpty())
          <div class="el-grupos">
              <h3>Os meus grupos</h3>
              <div class="el-grupos__container">
                @foreach($myGroups as $grupo)
                  <a href="{{ route('elearning.grupo', $grupo) }}" class="el-grupos__grupo">
                    @if($grupo->logo)
                      <img class="el-grupos__grupo__logo" src="{{$grupo->logo}}" alt="{{$grupo->nome}}">
                    @else
                      <span class="el-grupos__grupo__nome">{{$grupo->nome}}</span>
                    @endif
                  </a>
                @endforeach
              </div>
          </div>
        @endif

      </div>
    </div>
  @endauth

@endsection

resources/views/modules/list-component.blade.php
<div class="modules-list">
  @if($modules->isNotEmpty())
    <div class="row">
      @foreach($modules as $module)
        <div class="column col-12 col-sm-6 col-lg-4 col-xl-3">
          <div class="card mb-3 modules-list__item">
            <div class="card-img-top">
                @if($module->image)
                  <figure class="modules-list__item__image">
                    <img src="{{ $module->image }}">
                  </figure>
                @else
                  <figure class="modules-list__item__logo">
                    <div>
                      @if($module->grupo->logo)
                        <img src="{{ $module->grupo->logo }}">
                      @else
                        <svg>
                          <use xlink:href="{{ asset('img/sprite.svg') }}#igreja"/>
                        </svg>
                      @endif
                    </div>
                  </figure>
                @endif
            </div>
            <div class="card-body modules-list__item__body">
              <div class="media">
                <div class="media-body">
                  <h5 class="mb-0">{{ $module->name }}</h5>
                  <p class="text-muted">{{ $module->grupo->nome_curto }}</p>
                </div>
                @if($module->grupo->logo)
                  <img src="{{ $module->grupo->logo }}" class="ml-3" style="width: 48px;height: 48px;">
                @endif
              </div>

              <div class="modules-list__item__desc">
                {!! $module->description !!}
              </div>
              <a href="{{ route('elearning.modulos.show', $module) }}" class="card-link">
                Ver módulo
                <span class="far fa-arrow-right"></span>
              </a>

            </div>
          </div>
        </div>
      @endforeach
    </div>
  @else
    <div class="alert alert-secondary mb-0">
      {{ empty($empty_message) ? 'Não existem módulos.' : $empty_message }}
    </div>
  @endif
</div>

resources/views/modules/show.blade.php
@extends('elearning::layouts.main')

@php($hero = $module->image ?? Setting::get('grupo-'.$module->grupo->id.'-hero'))
@section('el.hero')
  <div class="el-hero @if($hero) has-cover @endif "
       @if($hero) style="background-image: url({{ $hero }})" @elseif($module->grupo->cor) style="background-color: {{ $module->grupo->cor }}" @endif
  >
    <div class="el-hero__body">
      <div class="container-fluid">
        <h1 class="el-hero__title">
          {{ $module->name }}
        </h1>
        <p class="el-hero__lead">
          {{ $module->grupo->nome_curto }}
        </p>
      </div>
    </div>
  </div>
@endsection

@section('el.content')

  <div class="el-section">
    <div class="container-fluid">

      <h3>
        Sobre este módulo
        @can('update', $module)
          @if($module->public)
            <span class="badge badge-info">Público</span>
          @endif
        @endcan
      </h3>
      <div class="content">
        {!! $module->description !!}
      </div>
      @can('update', $module)
        <a href="{{ route('elearning.modulos.edit', $module) }}" class="btn btn-secondary">
          <span class="fas fa-pencil"></span>
          <span>Editar</span>
        </a>
      @endcan

    </div>
  </div>

  <div class="el-section el-section--alt">
    <div class="container-fluid">

      <div class="row align-items-center mb-2">
        <h3 class="col mb-0">
          Lições
        </h3>
        <div class="col col-auto">
          <a href="{{ route('elearning.licoes.create') }}?module={{ $module->id }}" class="btn btn-secondary">
            <span class="far fa-plus"></span>
            <span class="d-none d-sm-inline">Criar</span>
          </a>
        </div>
      </div>

      @if($lessons->isNotEmpty())
        @include('elearning::lessons.list-component', ['lessons' => $lessons])
      @else
        <div class="alert alert-secondary">
          Não existem lições neste módulo.
        </div>
      @endif

      @if($notPublishedLessons->isNotEmpty())
        <h5 class="mt-4">Lições não publicadas</h5>
        @include('elearning::lessons.list-component', ['lessons' => $notPublishedLessons])
      @endif

    </div>
  </div>


@endsection